name: Maven Build/Test/Deploy JDK 17

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        server-id: central
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
    - name: Build and Deploy Snapshot with Maven
      run: |
        mvn -B clean deploy --file pom.xml
      env:
          MAVEN_USERNAME: ${{ secrets.MVN_SNAPSHOT_USER }}
          MAVEN_PASSWORD: ${{ secrets.MVN_SNAPSHOT_PW }}
